In [36]:
import pandas as pd
import numpy as np



In [37]:
from sklearn.datasets import load_iris
iris=load_iris()

In [38]:
df=pd.DataFrame(iris.data,columns=['sepal_length','sepal_width','petal_length','petal_width'])
df.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [39]:
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [43]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [45]:
X=df.iloc[:,:-1]
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [49]:
Y=df.iloc[:,-1:]
Y.head(2)

species
0  setosa
1  setosa

In [52]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=12)

In [53]:
X_train.head()

sepal_length  sepal_width  petal_length  petal_width
14           5.8          4.0           1.2          0.2
62           6.0          2.2           4.0          1.0
98           5.1          2.5           3.0          1.1
26           5.0          3.4           1.6          0.4
8            4.4          2.9           1.4          0.2

#Another Method of creating training and test data

In [55]:
#np.random generates random number between 0 and 1 
#.uniform generates uniform distribution
#75 %  is training
df['is_train']=np.random.uniform(0,1,len(df))<=.75
df.head()

sepal_length  sepal_width  petal_length  petal_width species  is train  \
0           5.1          3.5           1.4          0.2  setosa     False   
1           4.9          3.0           1.4          0.2  setosa     False   
2           4.7          3.2           1.3          0.2  setosa      True   
3           4.6          3.1           1.5          0.2  setosa      True   
4           5.0          3.6           1.4          0.2  setosa      True   

   is_train  
0      True  
1      True  
2      True  
3      True  
4      True

In [79]:
train,test=df[df['is_train']==True],df[df['is_train']==False]


In [83]:
print('the number of observations in training data is ',len(train))
print('the number of observations in test data is ',len(test))

the number of observations in training data is  116
the number of observations in test data is  34


In [90]:
#create a list of the feature column's names
features=df.columns[:-3]
features

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [103]:
#converting each species name into digits
y=pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2], dtype=int64)

In [105]:
#creating a random forest classifier
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_jobs=2,random_state=0)

#Training the classifier

clf.fit(train[features],y)


C:\Users\sameer\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [106]:
#applying the trained classifier to the testl
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2], dtype=int64)

In [107]:
#viewing the predicted probabilities of the observations
clf.predict_proba(test[features])

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.8, 0.2, 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.8, 0.2, 0. ],
       [1. , 0. , 0. ],
       [0.9, 0.1, 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.7, 0.3],
       [0. , 0.9, 0.1],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0.1, 0.9, 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0.1, 0.9],
       [0. , 0. , 1. ],
       [0. , 0.5, 0.5],
       [0. , 0. , 1. ],
       [0. , 0.3, 0.7],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ]])

In [110]:
#mapping names for the plants for each predicted
preds=iris.target_names[clf.predict(test[features])]

In [111]:
preds[0:25]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'virginica', 'virginica', 'virginica'], dtype='<U10')

In [114]:
#observing data from actual test data
test['species'].head()

6     setosa
7     setosa
11    setosa
16    setosa
18    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [115]:
#comparing predicted value and observed value
#creating confusion matrix
pd.crosstab(test['species'],preds)

col_0       setosa  versicolor  virginica
species                                  
setosa          13           0          0
versicolor       0           7          1
virginica        0           1         12

In [117]:
#better version
pd.crosstab(test['species'],preds,rownames=['Actual Species'],colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           7          1
virginica               0           1         12

In [118]:
from sklearn.metrics import classification_report

In [128]:
print(classification_report(preds,test['species']))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       0.88      0.88      0.88         8
   virginica       0.92      0.92      0.92        13

   micro avg       0.94      0.94      0.94        34
   macro avg       0.93      0.93      0.93        34
weighted avg       0.94      0.94      0.94        34



In [134]:
#deployment 
# what does the model predict for a flower with sepal length,width,
# contd: petal length and petal width of 5.3 cm, 2.4 cm, 1.9 cm and 3.0 cm


preds2=iris.target_names[clf.predict([[5.3,2.4,1.9,3.0],[8.3,1.4,1.4,2.0]])]
preds2

#answer is below

array(['versicolor', 'virginica'], dtype='<U10')